### PR TITLE
Dev by ddeck

### PR DESCRIPTION
**Pull request by DDECK**
Created basic elements of page

### CODE REVIEW

**Comment by DDhanushka** [comment]
good work, but

**Comment by DDECK** [comment]
> good work, but

what's wrong

**Comment by DDhanushka** [comment]
> > good work, but
> 
> what's wrong

Title is not correct

**Comment by DDECK** [comment]
Ok, i will fix it soon

**Comment by DDECK** [comment]
> Please change color green to black, you are ruining the page

Ok, sorry

**Comment by DDhanushka** [comment]
Great work

**Pull request merged**
